import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { ThemeProvider } from "@/providers/theme-provider"
import { cn } from "@/lib/utils"
import { QueryProvider } from "@/providers/query-provider"
import { CurrentUserProvider } from "@/providers/user-provider"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="pt-BR"
      suppressHydrationWarning
    >
      <body className={cn(
        `${geistSans.variable} ${geistMono.variable} antialiased`,
        "min-h-dvh flex"
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          <QueryProvider>
            <CurrentUserProvider>
              {children}
            </CurrentUserProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
